deselectAnnotation and annotationsPopUpEnabled
nitaliano/react-native-mapbox-gl pull request #418
Opened 2016-09-20 22:06 UTC by dapetcu21

Rebase of #386. Will test tomorrow to see if everything's ok, then merge.

2016-09-20 22:13 UTC, 1ec5 commented on ios/RCTMapboxGL/RCTMapboxGL.m
> +    BOOL _annotationsPopUpEnabled;
Make this a property so you don't need to implement the setter yourself.

2016-09-20 22:14 UTC, 1ec5 commented on ios/RCTMapboxGL/RCTMapboxGL.m
> +    _selectedAnnotation = annotation;
MGLMapView has a selectedAnnotations property for this.

2016-09-20 22:15 UTC, 1ec5 requested changes

2016-09-21 07:05 UTC, dapetcu21 commented
Tested this is working on iOS and Android. Merging.

2016-09-21 07:05 UTC, merged

2016-09-21 15:36 UTC, bigsassy commented
Thank you so much, @dapetcu21.  Any idea when this package will get updated in the npm registry?

2016-09-21 19:38 UTC, dapetcu21 commented
@bsudekum should have access to npm